name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run unit tests
        run: dotnet test
  
  test-compliance:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Start server in background
        run: dotnet run --project bases/Conduit.RestApi &

      - name: Test spec compliance
        run: ./test/run-api-tests.sh
        env:
          APIURL: http://localhost:5000/api

      - name: Stop server
        run: kill %1